simplify hyphen trigger action with --no-error-if-no-format

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -3,7 +3,7 @@
 # postinst maintainer script for the Debian tex-common package.
 #
 # Copyright (C) 2004 by Frank Küster <frank@kuesterei.ch>. 
-# Copyright (C) 2012 by Norbert Preining <preining@debian.org>
+# Copyright (C) 2012-2014 by Norbert Preining <preining@debian.org>
 #
 # This file is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -299,50 +299,33 @@ do_triggers()
           if dhit_texlive_binaries_configured; then
             if which kpsewhich >/dev/null; then
               if which fmtutil-sys >/dev/null; then
-                # code from postinst.tex
-                v=$(kpsewhich -var-value TEXMFSYSVAR)
-                c=$(kpsewhich -var-value TEXMFSYSCONFIG)
-                TEXMFVAR="$v"
-                TEXMFCONFIG="$c"
-                export TEXMFVAR TEXMFCONFIG
-                fmtcnffile=$(kpsewhich --format='web2c files' fmtutil.cnf)
-                X=$(grep "^[[:space:]]*latex[[:space:]]" $fmtcnffile || true)
-                if [ -n "$X" ] ; then
-                  # latex is installed so we can actually try to recreate
-                  # formats based on language.dat
-                  tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
-                  printf "Building latex-based formats --byhyphen $(kpsewhich language.dat).\n\tThis may take some time... "
-                  if fmtutil-sys --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.dat)" > $tempfile 2>&1 ; then
-                    rm -f $tempfile
-                    echo "done."
-                  else
-                    exec >&2
-                    echo
-                    echo "fmtutil-sys failed. Output has been stored in"
-                    echo "$tempfile"
-                    echo "Please include this file if you report a bug."
-                    echo
-                    exit 1
-                  fi
+                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                printf "Building latex-based formats --byhyphen $(kpsewhich language.dat).\n\tThis may take some time... "
+                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.dat)" > $tempfile 2>&1 ; then
+                  rm -f $tempfile
+                  echo "done."
+                else
+                  exec >&2
+                  echo
+                  echo "fmtutil-sys failed. Output has been stored in"
+                  echo "$tempfile"
+                  echo "Please include this file if you report a bug."
+                  echo
+                  exit 1
                 fi
-                Y=$(grep "^[[:space:]]*tex[[:space:]]" $fmtcnffile || true)
-                if [ -n "$Y" ] ; then
-                  # tex is installed so we can actually try to recreate
-                  # formats based on language.def
-                  tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
-                  printf "Building e-tex based formats --byhyphen $(kpsewhich language.def).\n\tThis may take some time... "
-                  if fmtutil-sys --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.def)" > $tempfile 2>&1 ; then
-                    rm -f $tempfile
-                    echo "done."
-                  else
-                    exec >&2
-                    echo
-                    echo "fmtutil-sys failed. Output has been stored in"
-                    echo "$tempfile"
-                    echo "Please include this file if you report a bug."
-                    echo
-                    exit 1
-                  fi
+                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                printf "Building e-tex based formats --byhyphen $(kpsewhich language.def).\n\tThis may take some time... "
+                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.def)" > $tempfile 2>&1 ; then
+                  rm -f $tempfile
+                  echo "done."
+                else
+                  exec >&2
+                  echo
+                  echo "fmtutil-sys failed. Output has been stored in"
+                  echo "$tempfile"
+                  echo "Please include this file if you report a bug."
+                  echo
+                  exit 1
                 fi
               fi
             fi
