postinst:trigger:run_hyphen: don't check for (la)tex in fmtutil.cnf, todos

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -252,44 +252,33 @@ run_hyphen()
                 TEXMFVAR="$v"
                 TEXMFCONFIG="$c"
                 export TEXMFVAR TEXMFCONFIG
-                fmtcnffile=$(kpsewhich --format='web2c files' fmtutil.cnf)
-                X=$(grep "^[[:space:]]*latex[[:space:]]" $fmtcnffile || true)
-                if [ -n "$X" ] ; then
-                    # latex is installed so we can actually try to recreate
-                    # formats based on language.dat
-                    tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
-                    printf "Building latex-based formats --byhyphen $(kpsewhich language.dat).\n\tThis may take some time... "
-                    if fmtutil-sys --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.dat)" > $tempfile 2>&1 ; then
-                        rm -f $tempfile
-                        echo "done."
-                    else
-                        exec >&2
-                        echo
-                        echo "fmtutil-sys failed. Output has been stored in"
-                        echo "$tempfile"
-                        echo "Please include this file if you report a bug."
-                        echo
-                        exit 1
-                    fi
+                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                printf "Building latex-based formats --byhyphen $(kpsewhich language.dat).\n\tThis may take some time... "
+                if fmtutil-sys --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.dat)" > $tempfile 2>&1 ; then
+                    rm -f $tempfile
+                    echo "done."
+                else
+                    exec >&2
+                    echo
+                    echo "fmtutil-sys failed. Output has been stored in"
+                    echo "$tempfile"
+                    echo "Please include this file if you report a bug."
+                    echo
+                    exit 1
                 fi
-                Y=$(grep "^[[:space:]]*tex[[:space:]]" $fmtcnffile || true)
-                if [ -n "$Y" ] ; then
-                    # tex is installed so we can actually try to recreate
-                    # formats based on language.def
-                    tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
-                    printf "Building e-tex based formats --byhyphen $(kpsewhich language.def).\n\tThis may take some time... "
-                    if fmtutil-sys --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.def)" > $tempfile 2>&1 ; then
-                        rm -f $tempfile
-                        echo "done."
-                    else
-                        exec >&2
-                        echo
-                        echo "fmtutil-sys failed. Output has been stored in"
-                        echo "$tempfile"
-                        echo "Please include this file if you report a bug."
-                        echo
-                        exit 1
-                    fi
+                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                printf "Building e-tex based formats --byhyphen $(kpsewhich language.def).\n\tThis may take some time... "
+                if fmtutil-sys --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.def)" > $tempfile 2>&1 ; then
+                    rm -f $tempfile
+                    echo "done."
+                else
+                    exec >&2
+                    echo
+                    echo "fmtutil-sys failed. Output has been stored in"
+                    echo "$tempfile"
+                    echo "Please include this file if you report a bug."
+                    echo
+                    exit 1
                 fi
             fi
         fi
