fix forgotten language.def handling in texmf-trigger action

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -191,6 +191,25 @@ do_triggers()
                     exit 1
                   fi
                 fi
+                Y=$(grep "^[[:space:]]*tex[[:space:]]" $fmtcnffile || true)
+                if [ -n "$Y" ] ; then
+                  # tex is installed so we can actually try to recreate
+                  # formats based on language.def
+                  tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                  printf "Building formats --byhyphen $(kpsewhich language.def).\n\tThis may take some time... "
+                  if fmtutil-sys --byhyphen "$(kpsewhich language.def)" > $tempfile 2>&1 ; then
+                    rm -f $tempfile
+                    echo "done."
+                  else
+                    exec >&2
+                    echo
+                    echo "fmtutil-sys failed. Output has been stored in"
+                    echo "$tempfile"
+                    echo "Please include this file if you report a bug."
+                    echo
+                    exit 1
+                  fi
+                fi
               fi
             fi
           fi
