add trigger support, bump version to 1.12~1

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -21,6 +21,7 @@ umask 022
 
 # Give a name to the first commandline argument
 action=$1
+trigger=$2
 
 . <:=${CONFMODULE}:>
 db_version 2.0
@@ -36,7 +37,80 @@ db_version 2.0
 #################################################################
 
 case $action in
-  configure|reconfigure)
+    triggered)
+        # currently we only support only triggers for updmap.d and
+        # language.d changes
+        # because all the other calls are quite fast 
+        # - call all the update-* scripts (it doesn't hurt)
+        # - go through all the triggers and call the respective fmtutil/updmap
+        #   calls.
+
+        # in any case call the update-* calls
+        update-updmap --quiet
+        update-language
+        update-fmtutil
+        case " $trigger " in
+            *" /etc/texmf/updmap.d "*) 
+                # do the processing
+	            # code from postinst.tex
+	            if dhit_libkpathsea_configured; then
+	                if which updmap-sys >/dev/null; then
+                        tempfile=$(mktemp -p /tmp updmap.XXXXXXXX)
+                        printf "Running updmap-sys. This may take some time... "
+                        if updmap-sys > $tempfile 2>&1 ; then
+                            rm -f $tempfile
+                            echo "done."
+                        else
+                            exec >&2
+                            echo
+                            echo "updmap-sys failed. Output has been stored in"
+                            echo "$tempfile"
+                            echo "Please include this file if you report a bug."
+                            echo
+                            echo "Sometimes, not accepting conffile updates in /etc/texmf/updmap.d"
+                            echo "causes updmap-sys to fail.  Please check for files with extension"
+                            echo ".dpkg-dist or .ucf-dist in this directory" 
+                            echo
+                            exit 1
+        	            fi
+                    fi
+                fi
+            ;;
+        esac
+        case " $trigger " in
+            *" /etc/texmf/language.d "*) 
+                # do the processing
+	            # code from postinst.tex
+                v=$(kpsewhich -var-value TEXMFSYSVAR)
+                c=$(kpsewhich -var-value TEXMFSYSCONFIG)
+                TEXMFVAR="$v"
+                TEXMFCONFIG="$c"
+                export TEXMFVAR TEXMFCONFIG
+                fmtcnffile=$(kpsewhich --format='web2c files' fmtutil.cnf)
+                X=$(grep "^[[:space:]]*latex[[:space:]]" $fmtcnffile || true)
+                if [ -n "$X" ] ; then
+                    # latex is installed so we can actually try to recreate
+                    # formats based on language.dat
+                    tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                    printf "Building formats --byhyphen $(kpsewhich language.dat).\n\tThis may take some time... "
+                    if fmtutil-sys --byhyphen "$(kpsewhich language.dat)" > $tempfile 2>&1 ; then
+                        rm -f $tempfile
+                        echo "done."
+                    else
+                        exec >&2
+                        echo
+                        echo "fmtutil-sys failed. Output has been stored in"
+                        echo "$tempfile"
+                        echo "Please include this file if you report a bug."
+                        echo
+                        exit 1
+                    fi
+                fi
+            ;;
+        esac
+    ;;
+      
+    configure|reconfigure)
 
 # is there a file /etc/texmf/language.dat already? Move it out of the way
     if [ -f $OLD_LDAT ]; then
@@ -220,6 +294,9 @@ esac
 
 #DEBHELPER#
 
-# Local Variables:
-# mode: shell-script
-# End:
+### Local Variables:
+### perl-indent-level: 4
+### tab-width: 4
+### indent-tabs-mode: nil
+### End:
+# vim:set tabstop=4 expandtab: #
