add two new triggers for all/refresh format build

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -332,6 +332,60 @@ do_triggers()
           fi
         ;;
     esac
+    # do NOT merge these two cases into one, from dpkg's trigger.txt:
+    # Generally each trigger name should be tested for separately, as the
+    # postinst will often be called for several triggers at once.
+    case " $trigger " in
+        *" texmf-fmtrefresh "*) 
+          if dhit_texlive_binaries_configured; then
+            if which kpsewhich >/dev/null; then
+              if which fmtutil-sys >/dev/null; then
+                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                printf "Refreshing all formats.\n\tThis may take some time... "
+                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --refresh > $tempfile 2>&1 ; then
+                  rm -f $tempfile
+                  echo "done."
+                else
+                  exec >&2
+                  echo
+                  echo "fmtutil-sys failed. Output has been stored in"
+                  echo "$tempfile"
+                  echo "Please include this file if you report a bug."
+                  echo
+                  exit 1
+                fi
+              fi
+            fi
+          fi
+        ;;
+    esac
+    # do NOT merge these two cases into one, from dpkg's trigger.txt:
+    # Generally each trigger name should be tested for separately, as the
+    # postinst will often be called for several triggers at once.
+    case " $trigger " in
+        *" texmf-fmtall "*) 
+          if dhit_texlive_binaries_configured; then
+            if which kpsewhich >/dev/null; then
+              if which fmtutil-sys >/dev/null; then
+                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
+                printf "Rebuilding all formats.\n\tThis may take some time... "
+                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --all > $tempfile 2>&1 ; then
+                  rm -f $tempfile
+                  echo "done."
+                else
+                  exec >&2
+                  echo
+                  echo "fmtutil-sys failed. Output has been stored in"
+                  echo "$tempfile"
+                  echo "Please include this file if you report a bug."
+                  echo
+                  exit 1
+                fi
+              fi
+            fi
+          fi
+        ;;
+    esac
 }
 
 
