* changelog editing: fix wrong bugnumber in last upload [frank]   * Add a more verbose explanation to the warning when updmap-sys failed     (closes: #397717), and echo errors to stderr. [frank]

diff --git a/scripts/postinst-tex b/scripts/postinst-tex
--- a/scripts/postinst-tex
+++ b/scripts/postinst-tex
@@ -22,10 +22,15 @@ dhit_create_fontmaps ()
         rm -f $tempfile
         echo "done."
     else
+        exec >&2
         echo
         echo "updmap-sys failed. Output has been stored in"
         echo "$tempfile"
         echo "Please include this file if you report a bug."
+	echo
+	echo "Sometimes, not accepting conffile updates in /etc/texmf/updmap.d"
+	echo "causes updmap-sys to fail.  Please check for files with extension"
+	echo ".dpkg-dist or .ucf-new in this directory" 
         echo
         exit 1
     fi
@@ -59,6 +64,7 @@ dhit_build_format ()
         rm -f $tempfile
         echo "done."
     else
+        exec >&2
         echo
         echo "fmtutil-sys failed. Output has been stored in"
         echo "$tempfile"
diff --git a/scripts/postinst-texfonts b/scripts/postinst-texfonts
--- a/scripts/postinst-texfonts
+++ b/scripts/postinst-texfonts
@@ -19,6 +19,7 @@ dhitf_update_lsr_files ()
         rm -f $tempfile
 	echo " done."
     else
+        exec >&2
     	echo
 	echo "mktexlsr failed. Output has been stored in"
 	echo "$tempfile"
@@ -36,10 +37,15 @@ dhitf_create_fontmaps ()
     	rm -f $tempfile
 	echo " done."
     else
+        exec >&2
     	echo
 	echo "updmap-sys failed. Output has been stored in"
 	echo "$tempfile"
 	echo "Please include this file if you report a bug."
+	echo
+	echo "Sometimes, not accepting conffile updates in /etc/texmf/updmap.d"
+	echo "causes updmap-sys to fail.  Please check for files with extension"
+	echo ".dpkg-dist or .ucf-new in this directory" 
 	echo
 	exit 1
     fi
