add update-* calls to postinst-tex, it was lost when I eliminated postinst-texlsr, where those were called in any case

diff --git a/scripts/postrm-tex b/scripts/postrm-tex
--- a/scripts/postrm-tex
+++ b/scripts/postrm-tex
@@ -26,9 +26,44 @@ dhit_call_update_texmf_config ()
     fi
 }
 
+dhit_check_run_without_errors ()
+{
+    silent=0
+    if [ "$1" = "-silent" ] ; then
+        silent=1
+        shift
+    fi
+    if which "$1" >/dev/null; then
+        tempfile=$(mktemp -p /tmp checkrun.XXXXXXXX)
+        if [ $silent = 0 ] ; then
+            printf "Running '$*'.\nThis may take some time..."
+        fi
+        set +e
+        if "$@" > $tempfile 2>&1 ; then
+            rm -f $tempfile
+            [ $silent = 0 ] && echo " done."
+        else
+            echo
+            echo "$* failed. Output has been stored in"
+            echo "$tempfile"
+            echo "If tex-common is not configured you can ignore this error" \
+                 "message!"
+            echo "Otherwise, please include this file if you report a bug."
+            echo
+        fi
+        set -e
+    fi
+
+    return 0
+}
+
 
 case "$1" in
     remove|disappear)
+        # It doesn't hurt to call all of them.
+        dhit_check_run_without_errors -silent update-updmap --quiet
+        dhit_check_run_without_errors -silent update-language
+        dhit_check_run_without_errors -silent update-fmtutil
         for i in #WHATTODO# ; do
             if [ "$i" = lsr ] ; then
                 dhit_call_update_texmf_config lsr
